Sprint2.restaurantes.find({});
Sprint2.restaurantes.find({},{"restaurant_id":1, "name":1, "borough":1, "cuisine":1});
Sprint2.restaurantes.find({},{"restaurant_id":1, "name":1, "borough":1, "cuisine":1, "_id":0});
Sprint2.restaurantes.find({},{"restaurant_id": 1,"name": 1,"borough": 1, "address.zipcode": 1, "_id": 0});
Sprint2.restaurantes.find({"borough": "Bronx"});
Sprint2.restaurantes.find({"borough": "Bronx"}).limit(5);
Sprint2.restaurantes.find({"borough": "Bronx"}).skip(5).limit(5);
Sprint2.restaurantes.find({"grades.score": {$gt: 90}});
Sprint2.restaurantes.find({"grades.score" : {$gt: 80, $lt: 100}});
Sprint2.restaurantes.find({"address.coord.0" : {$lt: -95.754168}});
Sprint2.restaurantes.find({ $and:[{"cuisine": {$ne: "American"}}, {"grades.score": {$gt: 70}}, {"address.coord.0": {$lt: -65.754168}}]});
Sprint2.restaurantes.find({"cuisine": {$ne: "American"}, "grades.score": {$gt: 70}, "address.coord.0": {$lt: -65.754168}});
Sprint2.restaurantes.find({ $and: [{"cuisine": {$ne: "American"}}, {"grades.grade":"A"}, {"borough": {$ne: "Brooklyn"}}]}). sort({"cuisine": -1});
Sprint2.restaurantes.find({"name": {$regex: "^Wil"}}, {"_id":0,"restaurant_id":1, "name":1, "borough":1, "cuisine":1});
Sprint2.restaurantes.find({"name": {$regex: "ces$"}}, {"_id":0,"restaurant_id":1, "name":1, "borough":1, "cuisine":1});
Sprint2.restaurantes.find({"name": {$regex: "Reg"}}, {"_id":0,"restaurant_id":1, "name":1, "borough":1, "cuisine":1});
Sprint2.restaurantes.find({$and:[{ "borough": "Bronx" }, {$or: [{"cuisine": "American"}, {"cuisine": "Chinese"}]}]},{"name":1,"cuisine":1,"borough":1});
Sprint2.restaurantes.find({$or:[{ "borough": "Bronx" },{ "borough": "Staten Island" },{ "borough": "Queens" },{ "borough": "Brooklyn" }]},{"_id":0,"restaurant_id":1, "name":1, "borough":1, "cuisine":1});